# Generated by Django 5.1.7 on 2026-09-03 17:43

import vulndb.apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setup_completed', models.BooleanField(default=False)),
                ('setup_step', models.PositiveSmallIntegerField(default=1)),
                ('organization_name', models.CharField(blank=True, default='', max_length=255)),
                ('local_id_prefix', models.CharField(default='ACME', max_length=16)),
                ('product_name', models.CharField(default='VULNDB', max_length=64)),
                ('login_title', models.CharField(blank=True, default='Вход в VULNDB', max_length=255)),
                ('login_text', models.TextField(blank=True, default='Локальная база данных уязвимостей')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/', validators=[vulndb.apps.core.models.validate_logo_file])),
                ('accent_color', models.CharField(default='#0a7ab8', max_length=16)),
                ('sidebar_color', models.CharField(default='#1b2430', max_length=16)),
                ('nvd_api_key', models.CharField(blank=True, default='', max_length=128)),
                ('nvd_enabled', models.BooleanField(default=True)),
                ('nvd_sync_interval_minutes', models.PositiveIntegerField(default=60)),
                ('kev_enabled', models.BooleanField(default=True)),
                ('kev_sync_interval_minutes', models.PositiveIntegerField(default=360)),
                ('bdu_enabled', models.BooleanField(default=True)),
                ('bdu_xlsx_url', models.URLField(default='https://bdu.fstec.ru/files/documents/vullist.xlsx', max_length=512)),
                ('bdu_sync_interval_minutes', models.PositiveIntegerField(default=1440)),
                ('bdu_verify_ssl', models.BooleanField(default=False)),
                ('mail_provider', models.CharField(blank=True, choices=[('smtp', 'SMTP'), ('exchange', 'Exchange'), ('office365', 'Office 365'), ('gmail', 'Gmail')], default='smtp', max_length=32)),
                ('mail_smtp_host', models.CharField(blank=True, default='', max_length=255)),
                ('mail_smtp_port', models.PositiveIntegerField(default=587)),
                ('mail_smtp_user', models.CharField(blank=True, default='', max_length=255)),
                ('mail_smtp_password', models.CharField(blank=True, default='', max_length=255)),
                ('mail_use_tls', models.BooleanField(default=True)),
                ('mail_from_address', models.EmailField(blank=True, default='', max_length=254)),
                ('mail_exchange_server', models.CharField(blank=True, default='', max_length=255)),
                ('mail_office365_tenant', models.CharField(blank=True, default='', max_length=255)),
                ('mail_gmail_app_password', models.CharField(blank=True, default='', max_length=255)),
                ('mail_enabled', models.BooleanField(default=False)),
                ('telegram_bot_token', models.CharField(blank=True, default='', max_length=255)),
                ('telegram_enabled', models.BooleanField(default=False)),
                ('telegram_default_chat_id', models.CharField(blank=True, default='', max_length=64)),
                ('auth_local_enabled', models.BooleanField(default=True)),
                ('auth_google_enabled', models.BooleanField(default=False)),
                ('auth_sso_enabled', models.BooleanField(default=False)),
                ('auth_ldap_enabled', models.BooleanField(default=False)),
                ('db_host', models.CharField(blank=True, default='', max_length=255)),
                ('db_port', models.PositiveIntegerField(default=5432)),
                ('db_name', models.CharField(blank=True, default='', max_length=128)),
                ('db_user', models.CharField(blank=True, default='', max_length=128)),
                ('db_sslmode', models.CharField(blank=True, default='prefer', max_length=32)),
                ('db_configured', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Системные настройки',
                'verbose_name_plural': 'Системные настройки',
            },
        ),
    ]
